apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis_health.sh: |
{{- include "redis_health.sh" . | nindent 4 }}
  config-init.sh: |
{{- include "redis_init.sh" . | nindent 4 }}
