apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: tcp-server
      port: {{ .Values.redis.port }}
      protocol: TCP
      targetPort: redis
  selector:
    release: {{ .Release.Name }}
    app: {{ include "redis.name" . }}
