apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis.labels" . | nindent 8 }}
        release: {{ .Release.Name }}
        app: {{ include "redis.name" . }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: config-init
          image: "{{ .Values.configInitImage.repository }}:{{ .Values.configInitImage.tag }}"
          imagePullPolicy: {{ .Values.configInitImage.pullPolicy }}
          command:
            - sh
            - -c
            - /scripts/config-init.sh
          volumeMounts:
            - name: redis-scripts
              mountPath: /scripts
              readOnly: true
            - name: redis-config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
      containers:
        - name: redis
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.redis.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.redis.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.redis.livenessProbe.failureThreshold }}
            exec:
              command:
                - sh
                - -c
                - /scripts/redis_health.sh
          readinessProbe:
            initialDelaySeconds: {{ .Values.redis.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.redis.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.redis.readinessProbe.failureThreshold }}
            exec:
              command:
                - sh
                - -c
                - /scripts/redis_health.sh
          startupProbe:
            initialDelaySeconds: {{ .Values.redis.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.redis.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.redis.startupProbe.failureThreshold }}
            exec:
              command:
                - sh
                - -c
                - /scripts/redis_health.sh
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: redis-scripts
          configMap:
            name: {{ include "redis.fullname" . }}-scripts
            defaultMode: 0755
        - name: redis-config
          configMap:
            name: {{ include "redis.fullname" . }}-config
            defaultMode: 0755
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.persistence.size }}
     
