apiVersion: v2
name: redis-chart
description: A customized redis chart for kubernetes deployments
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://github.com/jhua04/helm-charts/tree/main/images/redis.png
keywords:
  - redis
  - cache
  - database
  - key-value
home: https://jhua04.github.io
sources:
  - https://github.com/jhua04/helm-charts/redis-chart
maintainers:
  - name: Jie Hua
    email: jhua04@gmail.com